import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1280, height: 760 } });
const errs = []; p.on('pageerror', (e) => errs.push(String(e)));
await p.goto('http://localhost:8095/');
await p.waitForTimeout(400);
await p.click('text=Write one in the browser');
await p.waitForTimeout(3000);
console.log('editor from the published site:', await p.textContent('#stat'));
console.log('errors:', errs);
await b.close();
